# ---------------------------------------------------    
# Binary
input_boolean:
  notify_vent:
    name: Ventilate
    initial: off
    icon: mdi:air-filter
  notify_block:
    name: Blocked
    initial: off
    icon: mdi:block-helper
  allautomation:
    name: GroupAllAutomation
    initial: on
    icon: mdi:block-helper
  ptc_binary:
    name: ptc_b
    initial: on
    icon: mdi:radiator
  sleeperb:
    initial: off
    name: sleep Nextion(1)
  wakerb:
    initial: off
    name: wake up Nextion(0)
# ---------------------------------------------------    
  


# For nextion Dim and sleep control
input_text:
  dim:
    initial: 100
    name: dim_Nextion




























